name: pie_spider_pet
description: "Windows Spider Pet Project"
publish_to: 'none'

version: 0.0.3+3

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # 상태 관리
  flutter_riverpod: ^2.1.3

  # 윈도우 창 관리
  window_manager: ^0.3.8

  # 이벤트 제어
  mouse_event: ^0.2.1
  flutter_auto_gui: ^0.0.3

  # 모니터 정보
  screen_retriever: ^0.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/